// Generated by CoffeeScript 2.3.1
(function() {
  var SampleClass, _, assert, path, root, test;

  assert = require('assert');

  _ = require('lodash');

  ({test} = require('ava'));

  path = require('path');

  root = require('rrq').root();

  SampleClass = require(root);

  test('SampleClass.test()', (t) => {
    var sample;
    sample = SampleClass.test();
    return t.deepEqual(sample, {
      a: 2,
      b: 'sample text'
    });
  });

  // t.true sample is {a: 2,b: 'sample text'}
  test('package.json', (t) => {
    var pj;
    pj = require(path.join(root, 'package.json'));
    return t.is(pj.devDependencies.coffeescript, '^2.2.3');
  });

}).call(this);
