// Generated by CoffeeScript 2.2.4
(function() {
  var SampleClass, _, args2, root;

  _ = require('lodash');

  root = require('rrq').root();

  args2 = require('args2');

  SampleClass = class SampleClass {
    constructor(arg) {
      this.arg = arg;
    }

    static test() {
      return {
        a: 2,
        b: 'sample text'
      };
    }

  };

  module.exports = SampleClass;

}).call(this);
