// Generated by CoffeeScript 2.3.1
(function() {
  var SampleClass, _;

  _ = require('lodash');

  SampleClass = class SampleClass {
    constructor(arg) {
      this.arg = arg;
    }

    static test() {
      return {
        a: 2,
        b: 'sample text'
      };
    }

  };

  module.exports = SampleClass;

}).call(this);
